/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// noinspection JSUnusedGlobalSymbols
// Generated by unplugin-auto-import
// biome-ignore lint: disable
export {}
declare global {
  const DialogPlugin: typeof import('tdesign-vue-next')['DialogPlugin']
  const MessagePlugin: typeof import('tdesign-vue-next')['MessagePlugin']
  const TENANT_NAME: typeof import('tdesign-vue-next')['ENANT_NAME']
}
