/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    Example: typeof import('./src/components/rich-text-editor/example.vue')['default']
    MoreAdd: typeof import('./src/components/more-add/index.vue')['default']
    Privacy: typeof import('./src/components/agreement/privacy.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Service: typeof import('./src/components/agreement/service.vue')['default']
  }
}
